namespace:
    name: sandbox
service:
    port: 4111
    targetPort: 3111
    protocol: TCP
    type: ClusterIP
image:
    repository: abenda/techtrends
    tag: latest
    pullPolicy: IfNotPresent
replicaCount: 1
resources:
    requests:
        cpu: "250m"
        memory: "64Mi"
    limit:
        cpu: "500m"
        memory: "128Mi"
containerPort: 3111
livenessProbe:
    path: /healthz
    port: 3111
readynessProbe:
    path: /healthz
    port: 3111